on: push
name: CI
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: Bogdanp/setup-racket@v1.9
      with:
        architecture: 'x64'
        distribution: 'full'
        variant: 'CS'
        version: '8.7'
    - run: raco pkg install --auto --batch messagepack-lib/ messagepack-test/ messagepack/
    - run: raco test messagepack-test/
